### ISSUE TITLE
In metabase it is not taking up the password , i had given the right credentials

### ISSUE THREAD

**Issue by Utk98** [Drill4J/Drill4J#251] opened 2024-09-02 12:52 UTC
# In metabase it is not taking up the password , i had given the right credentials

## Description

In metabase it is not taking up the password , i had given the right credentials 
user@user.user
useruser1.

## Details

1. Attach full log files of your Application Under Test. Make sure it includes Drill4J Agent ASCII logo followed by version 
   

2. Describe your tech stack (for both application and tests) 
   - OS: 
   - Tech stack: 

## Screenshots

![Screenshot (450)](https://github.com/user-attachments/assets/abb008f3-608f-42b3-b893-3ab90c9f9cc9)

**Comment by RomanDavlyatshin** [comment] 2024-09-02 13:08
I assume you are following the [Getting Started - Local Deployment](https://drill4j.github.io/docs/getting-started/local-deployment#deploy-core-drill4j-services)
I am unable to reproduce the issue.
The following credentials work for me:
```
user@user.user
useruser1
```
Please not there is no dot "." character at the end of the password

**Comment by RomanDavlyatshin** [comment] 2024-09-02 13:11
@Utk98 just to be sure - have you correctly placed the `db-init/data.sql` as described in the instruction?

**Comment by Utk98** [comment] 2024-09-02 14:18
I am following the instructions given in "https://github.com/Drill4J/realworld-demo",and .sql file is already present there

**Comment by RomanDavlyatshin** [comment] 2024-09-02 15:17
@Utk98 I am confused about what are you trying to achieve:
1. Are you trying to run Drill4J demo?
2. Or are you trying to configure Drill4J for your application

If you are trying to deploy Drill4J for _your application_ - please follow the instructions from the docs (link above). The demo is not an installation instruction. ".sql" files provided in demo won't work for your application - they are demo-specific

**Comment by Utk98** [comment] 2024-09-04 08:59
@RomanDavlyatshin  I had configured with it , and followed the documentation , but facing a problem that container  ghcr.io/drill4j/admin:0.9.0  is not running the logs of it are -- 2024-09-04 08:23:43.244 [main] INFO  Application - Autoreload is disabled because the development mode is off.
2024-09-04 08:23:44.907 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2024-09-04 08:23:45.560 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2024-09-04 08:23:45.957 [main] INFO  o.f.c.i.license.VersionPrinter - Flyway Community Edition 8.4.1 by Redgate
2024-09-04 08:23:45.958 [main] INFO  o.f.c.i.d.base.BaseDatabaseType - Database: jdbc:postgresql://postgres:5432/postgres (PostgreSQL 14.1)
Exception in thread "main" org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Migration checksum mismatch for migration version 1
-> Applied to database : 1806852507
-> Resolved locally    : 935441267. Either revert the changes to the migration, or run repair to update the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:131)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:214)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
	at com.epam.drill.admin.auth.config.AuthDatabaseConfig.init(AuthDatabaseConfig.kt:38)
	at com.epam.drill.admin.DrillAdminApplicationKt.initDB(DrillAdminApplication.kt:166)
	at com.epam.drill.admin.DrillAdminApplicationKt.module(DrillAdminApplication.kt:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:207)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
	at io.ktor.server.engine.internal.CallableUtilsKt.callFunctionWithInjection(CallableUtils.kt:119)
	at io.ktor.server.engine.internal.CallableUtilsKt.executeModuleFunction(CallableUtils.kt:36)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:332)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:356)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.launchModuleByName(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$launchModuleByName(ApplicationEngineEnvironmentReloading.kt:32)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:312)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:338)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:150)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:277)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:216)
	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:23)
.Please help

**Comment by RomanDavlyatshin** [comment] 2024-09-08 12:27
I assume the instructions from realworld-demo worked for you and you managed to sign in.

The `FlywayValidateException: Validate failed: Migrations have failed validation Migration checksum mismatch for migration version 1` error indicates that you have PostgreSQL DB created with older version of Drill4J which is not compatible with the current one. The solution is to delete the old PostgreSQL DB volume and make sure you have a clean installation.

Closing the issue as the original question was answered.

**Closed as completed by RomanDavlyatshin** 2024-09-08 12:27 UTC
